site_name: Optiseek
nav:
    - 'Home': index.md
    - 'Quick Start Examples': examples.md
    - 'optiseek API':
        - '.variables':
            - 'All Variable Types': variables.md
        - '.metaheuristics':
            - 'Population-Based Methods':
                - 'Particle Swarm Optimizer': particle_swarm_optimization.md
                - 'Differential Evolution': differential_evolution.md
                - 'Firefly Algorithm': firefly_algorithm.md
                - 'Mayfly Algorithm': mayfly_algorithm.md
                - 'Flying Foxes Algorithm': flying_foxes_algorithm.md
            - 'Local Search Methods':
                - 'Simulated Annealing': simulated_annealing.md
        - '.modelhelpers':
            - 'Penalty Constraints': penalty_constraints.md
            - 'Parameter Grid Search': parameter_grid_search.md
        - '.testfunctions':
            - 'Ackley Function': ackley.md
            - 'Booth Function': booth.md
            - 'Rosenbrock Function': rosenbrock.md
            - 'Wheeler''s Ridge': wheelers_ridge.md
theme: 
    name: readthedocs
    prev_next_buttons_location: None
    navigation_depth: 4
    collapse_navigation: True
    titles_only: True